// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertWordToExcel(arg1) {
  return window['go']['main']['App']['ConvertWordToExcel'](arg1);
}

export function ConvertWordToExcelFromBytes(arg1, arg2) {
  return window['go']['main']['App']['ConvertWordToExcelFromBytes'](arg1, arg2);
}

export function OpenWordFile() {
  return window['go']['main']['App']['OpenWordFile']();
}

export function ProcessDroppedFile(arg1) {
  return window['go']['main']['App']['ProcessDroppedFile'](arg1);
}
